### ISSUE TITLE
Research papers with the proposed Dataset, and dataset name

### ISSUE THREAD

**Issue by hsbehera** [abdelkarim-elhajjami/Software-Defect-Number-Prediction#1]
Hi Abdelkarim EL-HAJJAMI,

Can i get any research papers with this dataset or may I know the dataset name?

**Comment by abdelkarim-elhajjami** [comment]
Hello,
This is a dataset that I collected myself from the VSCode GitHub repository :  https://github.com/microsoft/vscode 
For simplicity, I have considered that the number of bugs in a version are the bugs that appeared between this version and the following version, which is not necessarily true but which gives a number quite close to the real number of bugs.
For the statistics related to the source code, I used sloc from the npm package. And for git related statistics like number of commits, number of developers, I used GitStats.

**Comment by hsbehera** [comment]
any research article regarding this dataset which u created?

**Comment by abdelkarim-elhajjami** [comment]
No, indeed it was just as part of a personal project.

**Comment by hsbehera** [comment]
Thank you
